### ISSUE TITLE
Question: Which font-types are supported?

### ISSUE THREAD

**Issue by Jigsaw5279** [ebdrup/html2pdf.it#27]
I just wanted to ask which font-types are supported, as it seems that if I use a custom font via '@font-face' (e.g. MetaWeb-Book) the final PDF uses DejaVu-Sans to render the font.
Is there a list available where I could pick a supported font which is similar to the one used?

**Comment by ebdrup** [comment]
I'm actually not sure what fonts are supported out of the box. I guess it has whatever fonts are installed on the heroku box. Can you not make it download the font?

Perhaps you should check the phantomjs docs. Phantom does the rendering.

**Comment by Jigsaw5279** [comment]
It seems like font-face is not supported in PhantomJS. So it's not an issue of this (btw really awesome) library
