### ISSUE TITLE
Your web site can't convert my web page((( 

### ISSUE THREAD

**Issue by AnthonyAkentiev** [ebdrup/html2pdf.it#28]
If i try to convert "www.adaperio.ru" web site - i am getting blank PDF file. Can you please help me with a clue? Maybe i need something to change in my HTML code? 

What might be the problem? 

Thank you for cool project!

**Comment by edm00se** [comment]
I just [attempted to load it up](http://www.html2pdf.it/?url=www.adaperio.ru&download=false&format=A4&orientation=portrait&margin=1cm) and saw a bunch of text with no images. Looking at the site directly, it appears to be loading quite a bit of assets via JS. This is great for lazy loading and decreasing time to "paint" for the browser, but it still means that your content is loading when the browser thinks it's all loaded. I'm sure there are ways of optimizing this for your use case, but it's probably beyond the scope of support here.

Here's what I saw from Chrome's DevTools when I inspected, you can see that the car_bg.png is still downloading by the time Chrome registers the page as loaded.
![loadtiming](https://cloud.githubusercontent.com/assets/622118/18590086/1db24200-7bf3-11e6-817d-6ef50c1e8351.png)
