### ISSUE TITLE
still ssl issue

### ISSUE THREAD

**Issue by gurix** [ebdrup/html2pdf.it#30]
I am using html2pdf.it for my project and had some trouble going online. 

i.e the following page https://laufbahndiagnostik.psychologie.zhaw.ch/de/helena/sessions/gXyg1rEdtVLh5lTolkO2JKNOd results 

```
Unable to load the address (null): https://laufbahndiagnostik.psychologie.zhaw.ch/de/helena/sessions/gXyg1rEdtVLh5lTolkO2JKNOd fail
```

What I did then was runnning a new instance on heroku in with I ignored ssl errors with `--ignore-ssl-errors=true`. That seems to be the trick but indicates that my certification is wrong. But as far as I can see is everything normal.

![https___laufbahndiagnostik_psychologie_zhaw_ch_de_helena_sessions_gxyg1redtvlh5ltolko2jknod](https://cloud.githubusercontent.com/assets/95456/8451055/5b6bd900-1fe0-11e5-9cb8-19dea8d43b3a.png)

I guess the problem is phantomjs because when I run everything locally It works fine. Any idea?

**Comment by serteckian** [comment]
I am having similar problem.

I have a dedicated web server with Plesk 11 and in which I have installed node.js and running html2pdf.it module. I have several sites in this server. When I try to convert one a page of one of these sites that has no ssl certificate, everything goes just fine. However, when I try to convert another page that does have ssl certificate, then I get the following error:
Unable to load the address (null): https://www.mysite.com/pagetoconvert fail

Any idea how to fix this?
Is html2pdf.it able to load ssl sites?

Thanks!

**Comment by gurix** [comment]
@serteckian I stopped using html2pdf and render my stuff via the gem wicked_pdf, so I avoid a separate node.js instance, therefore I can't tell any more.

**Comment by serteckian** [comment]
I finally was able to surmount this issue with .htaccess redirections, so that any element (e.g., background image) in my PDF was loaded through http, rather than https.

Anyway, I understand your movement and thank you very much for your response.

**Comment by edm00se** [comment]
At this time, the above specified link in the OP is returning a 404 network response code. As html2pdf.it works [with other https sites](http://www.html2pdf.it/?url=https%3A%2F%2Fencrypted.google.com%2F&download=false&format=A4&downloadToken=1479675554460&orientation=portrait&margin=1cm), closing this barring additional information.
