### ISSUE TITLE
What is html2pdf.it production phantomjs configuration?

### ISSUE THREAD

**Issue by coffy** [ebdrup/html2pdf.it#37]
Hi, 
this is not really issue but I am trying to implement pdf generation with phantomjs on nodejs server with git://github.com/sgentle/phantomjs-node.git module.
I am not doing anything fancy . I want 1 A4 page with 2 columns (in table layout). 1 column is text and 2nd column is horizontally aligned picture. Had to set it with background css property because _img_ tag was causing really weird results and picture was never proper size.

When I use your web tool it renders page correctly , when i use my implementation, which is just plain 

```
page.setContent(html, url, function(status, err){
            if (status !== 'success') return next(err);
                page.render(tmpFile, function() {
                    page.close();
                    return next(null, tmpFile);
                    //console.log('PDF file: '+ filename + ' was generated');
                });
        });
```

the top part of picture is on 1st page and the bottom part is rendered on 2nd page. What configuration you use for phantomjs ? pageSize, viewPort , margins?  

Thanks a lot, any help would be appreciated.

**Comment by ebdrup** [comment]
I tried using that module too but did not have the control I needed at the time. Take a look at the sourcecode for your other questions.

**Comment by edm00se** [comment]
@coffy You can find [the defaults taken here](https://github.com/ebdrup/html2pdf.it/blob/9542722412aa0170cfe1e3d7092eee20074bf42c/lib/webservices/pdf.js#L31-L46).

Excerpt defaults:
- paper format: A4
- page orientation: portrait
- page margin: 1cm
- zoom: 1x
