### ISSUE TITLE
unable to print pdf browser is showing "something broke"

### ISSUE THREAD

**Issue by vsagar9944** [ebdrup/html2pdf.it#39]
pdf: /home/ist-116/NodeServer/html2pdf.it-master/bin/phantomjs: 1: /home/ist-116/NodeServer/html2pdf.it-master/bin/phantomjs: Syntax error: "(" unexpected

Error: Wrong code: 2
    at ChildProcess.<anonymous> (/home/ist-116/NodeServer/html2pdf.it-master/lib/webservices/pdf.js:99:19)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Socket.<anonymous> (child_process.js:1183:11)
    at Socket.emit (events.js:107:17)
    at Pipe.close (net.js:485:12)
::ffff:127.0.0.1 - - [11/Dec/2015:14:16:27 +0000] "GET /?url=localhost%3A8080&download=false&format=A4&downloadToken=1449843387206&orientation=portrait&margin=1cm HTTP/1.1" 500 16 "http://localhost:8080/" "Mozilla/5.0 (X11; Linux i686) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.80 Safari/537.36"

**Comment by vsagar9944** [comment]
This issue is due to not accessible phantomjs path in pdf.js under lib folder .

**Comment by nareshdb** [comment]
So have you edited pdf.js? I am having the same problem...

**Comment by nareshdb** [comment]
I solved it myself. **Just comment out the path setter code in pdf.js** 
`if (process.platform === 'win32') {
	pdfExecutable = 'phantomjs.exe';
}
if (process.platform !== 'darwin') {
	pdfExecutable = path.resolve(path.join('bin', pdfExecutable));
}`

**Comment by ralmaraz** [comment]
> I solved it myself. **Just comment out the path setter code in pdf.js** if you are on linux, or set to whatever your OS supports. Ask below if you dont know your path...
> `if (process.platform === 'win32') { pdfExecutable = 'phantomjs.exe'; } if (process.platform !== 'darwin') { pdfExecutable = path.resolve(path.join('bin', pdfExecutable)); }`

Naresfb how did you resolve this? Im having this issue, tha app has bee deployed in heroku....but i cant find the solution to this....I get the message something broke
