### ISSUE TITLE
Local Installation authentication

### ISSUE THREAD

**Issue by arbh89** [ebdrup/html2pdf.it#41]
I have installed the service on my intranet, the problem that i am facing is when i try to convert a page that uses authentication, i am getting an error 401, how can i pass the user and password to the request and phantomjs process?

**Comment by ebdrup** [comment]
not sure, sorry. Check the phantoms docs.

**Comment by arbh89** [comment]
I found a solution that works for me here.  http://stackoverflow.com/a/15940361,

Thank you.
