### ISSUE TITLE
Composer support

### ISSUE THREAD

**Issue by ogrosko** [ebdrup/html2pdf.it#44]
Is it possible to add composer support?
Also add it to https://packagist.org/

**Comment by edm00se** [comment]
This is a node application which is not an npm compatible module, and as such is meant to be installed and run stand-alone. It does not seem to be something which should be registered in a PHP package repository. Node and any PHP processor are entirely separate runtimes with their own dependency mechanisms.

_If_ (which I'm not sure is very likely) this application were to ever be refactored into an [npm](https://www.npmjs.com/) module, you could write a wrapper to load it as a script resource from [unpkg.com](https://unpkg.com/) (formerly knownas npm cdn), though that would just be wrapping an HTML `<script>` tag.
