### ISSUE TITLE
Update to phantomjs >= 2.0 to support font face

### ISSUE THREAD

**Issue by l5** [ebdrup/html2pdf.it#47]
It would be great to have the phantomjs upgraded to a version >= 2.0. These versions support CSS font face, enabling the user to use nearly any font. 

In order to update manually, the only thing to do is, to download the current version of phantomjs and copy it into the _bin_ folder of the html2pdf.it installation.

**Comment by edm00se** [comment]
The latest in the `master` branch switches from requiring a system level peer dependency to using `phantomjs-brebuilt` via `npm`; the version included is currently at the 2.11 level, which should address this.
