### ISSUE TITLE
How to use this in Angulajs web application

### ISSUE THREAD

**Issue by RupenAnjaria** [ebdrup/html2pdf.it#51]
Any example on how to use this on AngularJS application?

**Comment by edm00se** [comment]
This is rather beyond the normal scope of the support of the project itself, as you're essentially asking a normal AngularJS question of how to use a service/factory/provider.

The short answer is, so long as you have the user's browser perform a network request against the endpoint of an instance of html2pdf.it and include the query parameter `download=true`, then it should cause the user to receive a file download.

As for AngularJS specifics, you could skip a service/factory/provider and perform an arbitrary [`$http.get` request](https://docs.angularjs.org/api/ng/service/$http#get), it would look something like:

```js
var endpoint = 'http://www.html2pdf.it/';
var link ='www.github.com';
$http.get(endpoint, {
  params: {
    url: link,
    download: true,
    format: 'A4',
    orientation: 'portrait',
    margin: '1cm'
  }
});
```

The live site for [html2pdf.it](http://www.html2pdf.it/) seems to not include the `Access-Control-Allow-Origin`, so while the above is legitimately a solid answer, you might need to park your running version of the html2pdf.it app behind a proxy to ensure it's added, or make your own fork.

If you don't want that hassle,  you could take the approach that downloading or viewing a PDF is/should be a user event, then clicking a button or link should be easier, as the origin won't be the page your Angular app is loading from, but the user's browser directly, meaning that a link with a computed path would work fine. Here's [an example using this implementation](http://embed.plnkr.co/fbKNQ5Wr4FVTwrCCl4Do/).
