### ISSUE TITLE
npm package 

### ISSUE THREAD

**Issue by greglbd** [ebdrup/html2pdf.it#54]
Is there any chance of getting an npm package with require dependencies so this can be added to an existing node project rather than just pulling the repo?

i was searching arround for something like `npm install html2pdf-it`

**Comment by edm00se** [comment]
If you want to bring it to another git based project, as-is, you could do so by adding it as a [git submodule](https://git-scm.com/docs/git-submodule). What you're describing, as a package installable from [npmjs.com](https://www.npmjs.com/) is rather more specifically for what one would expect as a [CommonJS style module](https://nodejs.org/docs/latest/api/modules.html). This project is built as a standalone server and is not set up as having a separate server versus module that could just be "plugged into" another server. This would be no small task to switch, so I wouldn't expect this to happen anytime soon. My reply from #42 is pertinent here.
