### ISSUE TITLE
'filename' parameter not working 

### ISSUE THREAD

**Issue by lihusha** [ebdrup/html2pdf.it#58]
when add parameter 'filename' to url and try to download opened pdf file, name is different added to url as parameter 'filename'

**Comment by hairypaulsack** [comment]
Have you tested this on multiple sites? It works fine for me! For example I used both of these to test it out:

`www.html2pdf.it/?url=http://www.skorks.com/2010/05/what-every-developer-should-know-about-urls/&download=true&filename=What Every Developer Should Know About URLs`

`www.html2pdf.it/?url=http://www.skorks.com/2010/05/what-every-developer-should-know-about-urls/&download=true&filename=What_Every_Developer_Should_Know_About_URLs`
